import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#023061',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#001b3d',
        'surface-tint': '#eec068',
        'primary-container': '#d4a853',
        'on-error': '#690005',
        'surface': '#16130d',
        'tertiary-fixed': '#d6e3ff',
        'secondary-container': '#584325',
        'error-container': '#93000a',
        'on-secondary': '#3f2d11',
        'surface-container-high': '#2e2923',
        'secondary': '#e0c29a',
        'inverse-surface': '#eae1d7',
        'on-secondary-fixed-variant': '#584325',
        'primary-fixed-dim': '#eec068',
        'on-surface': '#eae1d7',
        'error': '#ffb4ab',
        'surface-container-low': '#1f1b15',
        'on-primary-container': '#573d00',
        'surface-dim': '#16130d',
        'primary': '#f2c36b',
        'on-background': '#eae1d7',
        'background': '#16130d',
        'inverse-primary': '#7b5804',
        'on-secondary-fixed': '#281901',
        'on-secondary-container': '#cdb18a',
        'tertiary': '#afcbff',
        'outline-variant': '#4e4637',
        'surface-container-lowest': '#110e08',
        'secondary-fixed': '#fddeb5',
        'on-primary-fixed-variant': '#5d4200',
        'surface-container': '#231f19',
        'on-tertiary-container': '#1d4274',
        'outline': '#9b8f7e',
        'surface-container-highest': '#39342d',
        'on-primary': '#412d00',
        'surface-variant': '#39342d',
        'on-tertiary-fixed-variant': '#234779',
        'surface-bright': '#3d3831',
        'tertiary-container': '#8fb0e9',
        'inverse-on-surface': '#343029',
        'secondary-fixed-dim': '#e0c29a',
        'on-primary-fixed': '#271900',
        'primary-fixed': '#ffdea6',
        'tertiary-fixed-dim': '#a8c8ff',
        'on-surface-variant': '#d2c5b2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-desktop': '64px',
        'container-max': '1280px',
        'section-gap': '120px',
        'margin-mobile': '20px',
        gutter: '24px',
      },
      fontFamily: {
        'display-lg': ['Cormorant Garamond', 'serif'],
        'display-md': ['Cormorant Garamond', 'serif'],
        'headline-sm': ['Cormorant Garamond', 'serif'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'body-md': ['DM Sans', 'sans-serif'],
        'label-caps': ['DM Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '300' }],
        'display-md': ['48px', { lineHeight: '1.2', fontWeight: '300' }],
        'headline-sm': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1.0', letterSpacing: '0.2em', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}

export default config
