import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Dynamic colors (switch between dark/light via CSS vars)
        'background':             'rgb(var(--c-background) / <alpha-value>)',
        'surface':                'rgb(var(--c-surface) / <alpha-value>)',
        'on-surface':             'rgb(var(--c-on-surface) / <alpha-value>)',
        'on-background':          'rgb(var(--c-on-background) / <alpha-value>)',
        'on-surface-variant':     'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--c-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--c-surface-container-highest) / <alpha-value>)',
        'surface-container':      'rgb(var(--c-surface-container) / <alpha-value>)',
        'surface-container-low':  'rgb(var(--c-surface-container-low) / <alpha-value>)',
        'outline-variant':        'rgb(var(--c-outline-variant) / <alpha-value>)',
        'outline':                'rgb(var(--c-outline) / <alpha-value>)',
        'secondary-container':    'rgb(var(--c-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--c-on-secondary-container) / <alpha-value>)',

        // Fixed accent colors (same in dark and light)
        'primary':            '#f2c36b',
        'on-primary':         '#412d00',
        'primary-container':  '#d4a853',
        'primary-fixed':      '#ffdea6',
        'primary-fixed-dim':  '#eec068',
        'on-primary-fixed':   '#271900',
        'on-primary-fixed-variant': '#5d4200',
        'on-primary-container': '#573d00',
        'inverse-primary':    '#7b5804',
        'secondary':          '#e0c29a',
        'on-secondary':       '#3f2d11',
        'secondary-fixed':    '#fddeb5',
        'secondary-fixed-dim': '#e0c29a',
        'on-secondary-fixed': '#281901',
        'on-secondary-fixed-variant': '#584325',
        'surface-tint':       '#eec068',
        'surface-dim':        '#16130d',
        'surface-bright':     '#3d3831',
        'surface-variant':    '#39342d',
        'inverse-surface':    '#eae1d7',
        'inverse-on-surface': '#343029',
        'tertiary':           '#afcbff',
        'tertiary-fixed':     '#d6e3ff',
        'tertiary-fixed-dim': '#a8c8ff',
        'tertiary-container': '#8fb0e9',
        'on-tertiary':        '#023061',
        'on-tertiary-fixed':  '#001b3d',
        'on-tertiary-fixed-variant': '#234779',
        'on-tertiary-container': '#1d4274',
        'error':              '#ffb4ab',
        'on-error':           '#690005',
        'error-container':    '#93000a',
        'on-error-container': '#ffdad6',
        'surface-container-lowest': '#110e08',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-desktop': '64px',
        'container-max': '1280px',
        'section-gap': '120px',
        'margin-mobile': '20px',
        gutter: '24px',
      },
      fontFamily: {
        'display-lg':  ['Cormorant Garamond', 'serif'],
        'display-md':  ['Cormorant Garamond', 'serif'],
        'headline-sm': ['Cormorant Garamond', 'serif'],
        'body-lg':     ['DM Sans', 'sans-serif'],
        'body-md':     ['DM Sans', 'sans-serif'],
        'label-caps':  ['DM Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg':  ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '300' }],
        'display-md':  ['48px', { lineHeight: '1.2', fontWeight: '300' }],
        'headline-sm': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-lg':     ['18px', { lineHeight: '1.6', fontWeight: '300' }],
        'body-md':     ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps':  ['11px', { lineHeight: '1.0', letterSpacing: '0.2em', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}

export default config
